#!/bin/bash

#PBS -N MPI
#PBS -o OUT
#PBS -q teaching
#PBS -l nodes=1:ppn=8,walltime=00:05:00

#! Mail to user if job aborts
#PBS -m a

#! application name
application="stencil.exe"

#! Run options for the application
options="1024 1024 100"

###############################################################
### You should not have to change anything below this line ####
###############################################################

#! change the working directory (default is home directory)

cd $PBS_O_WORKDIR

echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
echo PBS job ID is $PBS_JOBID
echo This jobs runs on the following machines:
echo `cat $PBS_NODEFILE | uniq`

#! Create a machine file for MPI
cat $PBS_NODEFILE > machine.file.$PBS_JOBID

numnodes=`wc $PBS_NODEFILE | awk '{ print $1 }'`

#! Run the parallel MPI executable (nodes*ppn)
mpirun -np 1 -machinefile machine.file.$PBS_JOBID $application $options
mpirun -np 2 -machinefile machine.file.$PBS_JOBID $application $options
mpirun -np 3 -machinefile machine.file.$PBS_JOBID $application $options
mpirun -np 4 -machinefile machine.file.$PBS_JOBID $application $options
mpirun -np 5 -machinefile machine.file.$PBS_JOBID $application $options
mpirun -np 6 -machinefile machine.file.$PBS_JOBID $application $options
mpirun -np 7 -machinefile machine.file.$PBS_JOBID $application $options
mpirun -np 8 -machinefile machine.file.$PBS_JOBID $application $options
mpirun -np 9 -machinefile machine.file.$PBS_JOBID $application $options
mpirun -np 10 -machinefile machine.file.$PBS_JOBID $application $options
mpirun -np 11 -machinefile machine.file.$PBS_JOBID $application $options
mpirun -np 12 -machinefile machine.file.$PBS_JOBID $application $options
mpirun -np 13 -machinefile machine.file.$PBS_JOBID $application $options
mpirun -np 14 -machinefile machine.file.$PBS_JOBID $application $options
mpirun -np 15 -machinefile machine.file.$PBS_JOBID $application $options
mpirun -np 16 -machinefile machine.file.$PBS_JOBID $application $options
